FROM python:3.13-slim

WORKDIR /app

RUN pip install --upgrade --no-cache-dir "pip>=25" && \
    pip install --root-user-action=ignore --no-cache-dir "poetry>=2,<3"

COPY pyproject.toml poetry.lock* /app/

RUN poetry config virtualenvs.create false \
    && poetry install -vv \
       --no-root --no-interaction --no-ansi --no-cache

COPY . /app/

EXPOSE 7086

ARG RUN_MODE=dev
ENV RUN_MODE=${RUN_MODE}

COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
