services:
    web:
      build:
        context: .
        dockerfile: Dockerfile.dev
      container_name: python-clean-arch
      ports:
        - "7086:7086"
      depends_on:
        postgresql:
          condition: service_healthy
      environment:
        APP_NAME: python-clean-arch
        IS_DEVELOPMENT: true
        LOG_LEVEL: INFO
        DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgresql:5432/python_clean_arch
        ACCESS_TOKEN_EXPIRE_MINUTES: 30
        REFRESH_TOKEN_EXPIRE_DAYS: 7
        SHOULD_RESET_DATABASE: true
